//@version=4
study("MTV MTF", overlay=false, max_labels_count=500, max_bars_back=5000)
// percentage of portoflio, 
MIN_ENTER = 0.05
MAX_ENTER = 0.4

// Functions & Constants, GLOBAL
var mtvs_default_weighting_ratios = array.new_float(10) // 10 weighted array slots
var mtvs_default_weights = array.new_float(16) // 16 weighted array slots
var tp_bb_default_weights = array.new_float(4)
var tp_mtvd_default_weights = array.new_float(5)
var tp_mtvl_default_weights = array.new_float(6)

pos_calculator(pos) => pos*100/close // pos = percentage of account to enter...
decimal_place(val, dp) => round(val*pow(10, dp))/pow(10, dp) // 10^dp
index_counter(to_count, amount) => sum(to_count ? 1: 0, amount)
map_weight(weight, x0, x1, y0, y1) => x1 == x0 ? y1 : y0 + (weight-x0) * (y1-y0)/(x1-x0)

mtv_values() =>
	// Functions & Constants
    vol_8ema = ema(volume, 8)
    price_8ema = ema(close, 8)
    vol_13ema = ema(volume, 13) 
    price_13ema = ema(close, 13)
    price_20ema = ema(close, 20)
    price_20ema_stdev = stdev(close, 20)
    oc = open - close
    oc_13ema = ema(abs(oc), 13)
    oc_20ema = ema(abs(oc), 20)
    green_candle = oc < 0
    red_candle = oc > 0
    
    vol_8ema_roc = ((vol_8ema-vol_8ema[1])/vol_8ema)*100
    vol_8ema_roc_20ema_stdev = stdev(vol_8ema_roc, 20)
    vol_8ema_roc_20ema = ema(vol_8ema_roc, 20)
    engulfing_vol = vol_8ema_roc > vol_8ema_roc_20ema + vol_8ema_roc_20ema_stdev
    above_20ema = open > price_20ema and close > price_20ema
    above_3x20ema = index_counter(above_20ema, 3) == 3

    // VOLUME TRNED
    cng_vol_8ema = (vol_8ema[1]-vol_8ema)/vol_8ema
    cng_price_8ema = (price_8ema[1]-price_8ema)/price_8ema
    trend_bull = cng_vol_8ema < 0 and cng_price_8ema < 0
    trend_bull_dubious = cng_vol_8ema > 0 and cng_price_8ema < 0

    // MACD
    macd = price_8ema - price_13ema
    macd_signal = sma(macd, 3) // signal length is 3
    macd_13ema = ema(macd, 13)
    macd_bull = macd > macd_13ema
    macd_bull_dubious = macd > macd_signal
    
    // MACD TRENDING VOLUME = MTV
    // assigns each candle a major MTV value
    bull_1 = macd_bull and macd_bull_dubious and trend_bull
    
    // MTV Loops
    // for the weighted decay over the last 5, ..., ... candles
    bull_2_index5 = index_counter(bull_2, 5)
    green_colour = bull_1 or bull_2 or bull_3 or bull_4 or bull_5 or bull_6 // signal direction

    
    // MTV Dots - bull, removed bear
    // how strong the trend is, looks at wick size and candle size
    mtv_dot_bull = ((green_candle and abs(oc) > tr*0.45) and (bull_1 or bull_3 or bull_6)) or (
         (green_candle and abs(oc) > tr*0.3) and (bull_2 or bull_4)) or (
         bear_5 and green_candle and abs(oc) > tr*0.45)
    mtv_dot_bull_index5 = index_counter(mtv_dot_bull, 5) // for the weighted degay of trend strength

    bull_dots = mtv_dot_bull or mtv_dot_bull_index5 > 2 or mtv_dot_bull_index10 > 5
    bull_dot_s = mtv_dot_bull and not(mtv_dot_bull_index5 > 2 or mtv_dot_bull_index10 > 5)
    bull_dot_m = mtv_dot_bull_index5 > 2 and not(mtv_dot_bull_index10 > 5)
    bull_dot_l = mtv_dot_bull_index10 > 5

    // M*; [1,2,3,4,5]
    mtvd_m_total_bull = 0.0
    mtvd_m_weight_bull = 0.0
    
    if bull_dot_m 
        for i=0 to 4
            if mtv_dot_bull[i]
                mtvd_m_total_bull += 5-i
        mtvd_m_weight_bull :=
         (mtv_dot_bull ? mtvd_m_total_bull*1 :
         mtv_dot_bull[1] ? mtvd_m_total_bull*0.75 :
         mtv_dot_bull[2] ? mtvd_m_total_bull*0.5 : 0.0)/15
    
    mtvd_l_to_m_bull = bull_dot_l[1] and bull_dot_m and not(mtv_dot_bull[1])
    mtvd_m_weight_bull *=
     mtvd_l_to_m_bull ? 1.2 :
     mtvd_l_to_m_bull[1] ? 1.1 : 1.0

    // L*; [1,2,3,4,5,6,7,8,9,10]
    mtvd_l_total_bull = 0.0
    mtvd_l_weight_bull = 0.0
    if bull_dot_l 
        for i=0 to 9 
            if mtv_dot_bull[i]
                mtvd_l_total_bull += 10-i
        mtvd_l_weight_bull :=
         (mtv_dot_bull ? mtvd_l_total_bull*1 :
         mtv_dot_bull[1] ? mtvd_l_total_bull*0.85 :
         mtv_dot_bull[2] ? mtvd_l_total_bull*0.7 :
         mtv_dot_bull[3] ? mtvd_l_total_bull*0.55 :
         mtv_dot_bull[4] ? mtvd_l_total_bull*0.4 : 0.0)/55

    
    // MTV Signals 
    // bull, removed bear
    mtvs_current_index_bull = 15
    // 1
    if  bear_2[1] and bear_5
        mtvs_current_index_bull := 0
    if bear_2_index7 > 1 and index_counter(bear_5, 7) > 1     
        mtvs_current_index_bull := 1
    if (bear_2_index10 > 2 and bear_5_index10 > 3) or (bear_2_index10 > 3 and bear_5_index10 > 2)
        mtvs_current_index_bull := 2
    // 2, 2.2, 2.3
    mtvs_current_index_bull :=
     bull_3[1] and bull_2 ? 3 :
     bull_4[1] and bull_2 ? 4 :
     bull_4[1] and bull_3 ? 5 :
     bull_4[1] and bull_1 ? 6 :
     bull_6[1] and bull_1 ? 7 :
     bull_3[1] and bull_1 ? 8 : mtvs_current_index_bull
    // 2.4, 2.5, 2.8
    if (bull_2_index5 > 1 and bull_6_index5 > 0) or (bull_2_index5 > 0 and bull_6_index5 > 1)
        mtvs_current_index_bull := 9
    if (bull_2_index7 > 2 and bull_6_index7 > 1) or (bull_2_index7 > 1 and bull_6_index7 > 2)
        mtvs_current_index_bull := 10
    if bear_5_index10 > 0 and bear_1_index7 > 2 and bull_1[1]
        mtvs_current_index_bull := 11
    // 3
    if index_counter(bull_1, 5) > 1 and bull_2_index5 > 0
        mtvs_current_index_bull := 12
    if bull_1_index7 > 2 and bull_2_index7 > 1
        mtvs_current_index_bull := 13
    if (bull_1_index10 > 3 and bull_2_index10 > 2) or (bull_1_index10 > 2 and bull_2_index10 > 3)
        mtvs_current_index_bull := 14
    
    // weights
    var mtvs_last_index_bull = array.new_int(15)   
    var mtvs_adjusted_weights_bull = array.new_float(15)
    mtvs_last_index_val_bull = 0
    mtvs_range_bull = 0
    mtvs_adjusted_range_bull = 0.0
    for i=0 to 14
        mtvs_last_index_val_bull := mtvs_current_index_bull == i and mtvs_current_index_bull != mtvs_current_index_bull[1] ? 0 : array.get(mtvs_last_index_bull, i) + 1
        array.set(mtvs_last_index_bull, i, mtvs_last_index_val_bull)
        mtvs_range_bull :=
         i >= 0 and i <= 2 ? 50 :
         i >= 3 and i <= 8 ? 40 :
         i == 9 or i == 10 ? 30 : 
         i == 11 or i == 14 ? 20 : 
         i == 12 or i == 13 ? 10 : 0
        for j=1 to 5
            if int((mtvs_range_bull-1)/10) == j-1 and mtvs_last_index_val_bull < 10*j
                mtvs_adjusted_range_bull := array.get(mtvs_default_weighting_ratios, int(mtvs_last_index_val_bull/j))/21
                array.set(mtvs_adjusted_weights_bull, i, array.get(mtvs_default_weights, i)*mtvs_adjusted_range_bull)
            if mtvs_last_index_val_bull > mtvs_range_bull
                array.set(mtvs_adjusted_weights_bull, i, 0.0)

    
    // 20 EMA - bull, removed bear
    good_3x20ema_bull = index_counter(green_colour, 10) >= 7 and above_3x20ema
    good_3x20ema_weight_bull = index_counter(good_3x20ema_bull, 4) == 4 ? 1.5 : good_3x20ema_bull ? 1.2 : above_3x20ema ? 1.0 :
     not(above_3x20ema or below_3x20ema) ? 0.75 : 0.0
    

    // Run Up
    run_up_oc = index_counter(oc_13ema > oc_13ema[1], 20)
    run_up_vol = index_counter(vol_13ema > vol_13ema[1], 20)
    run_up_price = index_counter(price_13ema > price_13ema[1], 13)// index_counter(price_13ema[0] < price_13ema[1], 13) is the same as abs(run_up_price-13)
    run_up_bull = run_up_oc >= 9 and run_up_vol >= 9 and run_up_price == 13 and green_candle

    // bull, removed bear
    run_up_last_index_bull = barssince(run_up_bull)
    run_up_weight_bull = run_up_last_index_bull >= 20 ? 0.0 : (1-(0.05*run_up_last_index_bull))*pow(1.05, index_counter(run_up_bull[0] and run_up_bull[1], 7))
    
    
    // Engfuling aka Large E
    large_e_bull = (abs(oc) > oc_20ema*2 and engulfing_vol and green_candle)
    large_e_last50_bull = index_counter(large_e_bull, 50)
    large_e_bear = (abs(oc) > oc_20ema*2 and engulfing_vol and red_candle)
    large_e_last50_bear = index_counter(large_e_bear, 50) 
    large_e_last_index_either = barssince(large_e_bull or large_e_bear)
    
    // bull, removed bear
    large_e_good_bull = index_counter(green_colour, 5) >= 3 and large_e_bull and large_e_last50_bull <= 5 and large_e_last_index_either[1] > 15
    large_e_good_last_index_bull = barssince(large_e_good_bull)
    large_e_good_weight_bull = large_e_good_bull ? 1.0 : large_e_good_last_index_bull < 5 ? 0.65-(0.15*large_e_good_last_index_bull) : 0.0
    

    
    
    // TAKING PROFIT, TP TAKE PROFIT
    // TP Congruent AKA TPC
    // bull & SE bull, removed bear & SE bull
    tp_congruent_current_val_bull = 9
    tp_congruent_index_loop_bull = 0
    tp_congruent_weight_loop_bull = 0.0
    tp_congruent_weight_double_bull = 0.0
    tp_congruent_double_bull = 0
    var tp_congruent_last_index_bull = array.new_int(3)
    var tp_congruent_weight_bull = array.new_float(3)
    if bull_1 and green_candle
        if (open-low) > tr*0.5 // hammer
            tp_congruent_current_val_bull := 0
            tp_congruent_double_bull += 1
        if engulfing_vol and (high-close) < tr*0.3
            tp_congruent_current_val_bull := 1
            tp_congruent_double_bull += 1
    
    for i=0 to 1
        tp_congruent_index_loop_bull := tp_congruent_current_val_bull == i ? 0 : array.get(tp_congruent_last_index_bull, i) + 1
        array.set(tp_congruent_last_index_bull, i, tp_congruent_index_loop_bull)
        if tp_congruent_index_loop_bull <= 10
            tp_congruent_weight_loop_bull :=
             tp_congruent_current_val_bull == i and tp_congruent_current_val_bull[1] == i and tp_congruent_current_val_bull[2] == i ? (1.2+0.1*i)*1.3 :
             tp_congruent_current_val_bull == i and tp_congruent_current_val_bull[1] == i ? (1.2+0.1*i)*1.15 :
             tp_congruent_index_loop_bull == 0 ? (1.2+0.1*i) :
             array.get(tp_congruent_weight_bull, i) - (1.2+0.1*i)*(0.2-0.1*i)
            if tp_congruent_weight_loop_bull < 0.0
                tp_congruent_weight_loop_bull := 0.0
            if tp_congruent_double_bull != 2
                array.set(tp_congruent_weight_bull, i, tp_congruent_weight_loop_bull)
        else
            array.set(tp_congruent_weight_bull, i, 0.0)
    
    tp_congruent_index_loop_bull := tp_congruent_double_bull == 2 ? 0 : array.get(tp_congruent_last_index_bull, 2) + 1
    array.set(tp_congruent_last_index_bull, 2, tp_congruent_index_loop_bull)
    if array.get(tp_congruent_last_index_bull, 2) == 0
        tp_congruent_weight_double_bull := tp_congruent_weight_loop_bull*1.3
    else
        tp_congruent_weight_double_bull := array.get(tp_congruent_last_index_bull, 2) <= 10 ? tp_congruent_weight_double_bull[1] - 0.14 : 0.0
    array.set(tp_congruent_weight_bull, 2, tp_congruent_weight_double_bull)
    if tp_congruent_double_bull == 2
        tp_congruent_current_val_bull := 2
    

    
    // TAKING PROFIT BULL = SMALL ENTRY BEAR, FOR THE REST
    // Used to adjust weights
    // Bollinger Bands TP    
    // bull & SE bear, removed bear & SE bull
    tp_bb_current_val_bull = 9
    tp_bb_index_loop_bull = 0
    tp_bb_weight_loop_bull = 0.0
    tp_bb_weight2_loop_bull = 0.0
    var tp_bb_last_index_bull = array.new_int(4)
    var tp_bb_weight_bull = array.new_float(4)
    two_away_above = (high[1] < price_20ema[1] + price_20ema_stdev[1]*2 )and (high < price_20ema + price_20ema_stdev*2)
    bb_above_index1 = high[2] > price_20ema[2] + price_20ema_stdev[2]*2
    bb_above_index5 = index_counter(high[2] > price_20ema[2] + price_20ema_stdev[2]*2, 5)
    bb_above_index7 = index_counter(high[2] > price_20ema[2] + price_20ema_stdev[2]*2, 7)
    bb_above_index10 = index_counter(high[2] > price_20ema[2] + price_20ema_stdev[2]*2, 10)
    if two_away_above
        if bb_above_index1 and red_candle[1] and red_candle
            tp_bb_current_val_bull := 3
        if bb_above_index5 >= 3
            tp_bb_current_val_bull := 0
        if bb_above_index7 >= 5
            tp_bb_current_val_bull := 1
        if bb_above_index10 >= 7
            tp_bb_current_val_bull := 2
    
    for i=0 to 3
        tp_bb_index_loop_bull := tp_bb_current_val_bull == i ? 0 : array.get(tp_bb_last_index_bull, i) + 1
        array.set(tp_bb_last_index_bull, i, tp_bb_index_loop_bull)
        if tp_bb_index_loop_bull <= 10
            tp_bb_weight_loop_bull := array.get(tp_bb_default_weights, i)
            if i == 0 or i == 1
                tp_bb_weight2_loop_bull :=
                 tp_bb_current_val_bull == i and tp_bb_current_val_bull[1] == i and tp_bb_current_val_bull[2] == i ? tp_bb_weight_loop_bull*1.3 :
                 tp_bb_current_val_bull == i and tp_bb_current_val_bull[1] == i ? tp_bb_weight_loop_bull*1.15 :
                 tp_bb_index_loop_bull == 0 ? tp_bb_weight_loop_bull :
                 array.get(tp_bb_weight_bull, i) - tp_bb_weight_loop_bull*0.1
            if i == 2
                tp_bb_weight2_loop_bull :=
                 tp_bb_current_val_bull == i and tp_bb_current_val_bull[1] == i and tp_bb_current_val_bull[2] == i and tp_bb_current_val_bull[3] == i ?
                 tp_bb_weight_loop_bull*1.4 :
                 tp_bb_current_val_bull == i and tp_bb_current_val_bull[1] == i and tp_bb_current_val_bull[2] == i ? tp_bb_weight_loop_bull*1.25 :
                 tp_bb_current_val_bull == i and tp_bb_current_val_bull[1] == i ? tp_bb_weight_loop_bull*1.1 :
                 tp_bb_index_loop_bull == 0 ? tp_bb_weight_loop_bull :
                 array.get(tp_bb_weight_bull, i) - tp_bb_weight_loop_bull*0.1
            if i == 3
                tp_bb_weight2_loop_bull :=
                 tp_bb_index_loop_bull == 0 ? tp_bb_weight_loop_bull :
                 array.get(tp_bb_weight_bull, i) - tp_bb_weight_loop_bull*0.14286
            if tp_bb_weight2_loop_bull < 0.0
                tp_bb_weight2_loop_bull := 0.0
            array.set(tp_bb_weight_bull, i, tp_bb_weight2_loop_bull)
        else
            array.set(tp_bb_weight_bull, i, 0.0)
    

    
    // MTV Gulfing & MTV Wicky TP removed bull & SE bear, bear & SE bull - deleted looped conditions
    // MTV Candles TP removed bull & SE bear, bear & SE bull - deleted looped conditions
    // MTV Dots TP removed bull & SE bear, bear & SE bull - deleted looped conditions
    // MTV Lots TP removed bull & SE bear, bear & SE bull - deleted looped conditions
    

    // AGGREGATED Weight
    // MTVD
    // bull, bear removed
    mtvd_last_index_bull = barssince(bull_dot_m or bull_dot_l)
    mtvd_current_weight_bull = mtvd_m_weight_bull + mtvd_l_weight_bull*1.5
    var mtvd_ag_weight_bull = 0.0
    mtvd_ag_weight_bull := mtvd_last_index_bull >= 10 ? 0.0 :
     mtvd_current_weight_bull + mtvd_ag_weight_bull[mtvd_last_index_bull] - mtvd_ag_weight_bull[mtvd_last_index_bull]*(mtvd_last_index_bull+1)*0.1
    


    // MTVS
    // bull, bear removed
    mtvs_amount_1_bull = max(array.get(mtvs_adjusted_weights_bull, 0), array.get(mtvs_adjusted_weights_bull, 1), array.get(mtvs_adjusted_weights_bull, 2))
    mtvs_amount_1gd_bull = max(array.get(mtvs_adjusted_weights_bull, 0), array.get(mtvs_adjusted_weights_bull, 1))
    mtvs_amount_2_bull = 0.0
    mtvs_amount_2gd_bull = max(array.get(mtvs_adjusted_weights_bull, 9), array.get(mtvs_adjusted_weights_bull, 10))
    mtvs_amount_3_bull = max(array.get(mtvs_adjusted_weights_bull, 12), array.get(mtvs_adjusted_weights_bull, 13), array.get(mtvs_adjusted_weights_bull, 14))
    mtvs_amount_3gd_bull = max(array.get(mtvs_adjusted_weights_bull, 12), array.get(mtvs_adjusted_weights_bull, 13))
    mtvs_amount_2x_bull = 0.0
    for i=3 to 11
        if i >= 3 and i <= 10
            mtvs_amount_2_bull := max(mtvs_amount_2_bull, array.get(mtvs_adjusted_weights_bull, i))
        if i == 11 and array.get(mtvs_adjusted_weights_bull, i) > mtvs_amount_2x_bull
            mtvs_amount_2x_bull := array.get(mtvs_adjusted_weights_bull, i)
    
    mtvs_best_combo_bull = max(
     mtvs_amount_1_bull and mtvs_amount_2_bull and mtvs_amount_3_bull ? (mtvs_amount_1_bull + mtvs_amount_2_bull + mtvs_amount_3_bull)*1.75: 0.0,
     mtvs_amount_2_bull and mtvs_amount_3_bull and not(mtvs_amount_1_bull) ? (mtvs_amount_2_bull + mtvs_amount_3_bull)*1.45 : 0.0, ...)

    
    // TP Congruent, BB, MTVG, MTVW, MTVC, MTVD, MTVL.  removed bull & SE bear, bear & SE bull - deleted looped conditions
    tp_aggregated_weight_bull = mtvd_ag_weight_bull >= 4 ? (mtvd_ag_weight_bull-4)/4 : 0.0

    
    // ADJUSTED Weight
    // MTVD
    // bull, removed bear
    mtvd_adjusted_bull = mtvd_current_weight_bull
    if mtvd_ag_weight_bull >= 1.2 and mtvd_ag_weight_bull < 2
        mtvd_adjusted_bull := (mtvd_current_weight_bull + mtvd_ag_weight_bull)*0.5
    if mtvd_ag_weight_bear >= 4
        mtvd_adjusted_bull *= sqrt(mtvd_ag_weight_bear)*0.5
    for i=0 to 4
        mtvd_adjusted_bull -= array.get(tp_mtvd_weight_bull, i)*0.6
    
    if mtvd_adjusted_bull < 0 or mtvd_current_weight_bull < 0.5 or mtvd_ag_weight_bull > 3
        mtvd_adjusted_bull := 0.0

    
    // MTVS
    // bull, removed bear
    mtvs_adjusted_bull = mtvs_best_combo_bull
    mtvs_inlast5_index_bull = barssince(bull_2_index5 and index_counter(bull_5, 5))
    mtvs_inlast10_index_bear = min(array.get(mtvs_last_index_bear, 1), array.get(mtvs_last_index_bear, 2))
    mtvs_inlast15_index_bear = min(array.get(mtvs_last_index_bear, 9), array.get(mtvs_last_index_bear, 10),
     array.get(mtvs_last_index_bear, 12), array.get(mtvs_last_index_bear, 13))
    if mtvs_inlast5_index_bull < 5
        mtvs_adjusted_bull := mtvs_best_combo_bull - mtvs_best_combo_bull*0.2*(5-mtvs_inlast5_index_bull)*0.5
    if mtvs_inlast10_index_bear < 10
        mtvs_adjusted_bull := mtvs_best_combo_bull - mtvs_best_combo_bull*0.1*(10-mtvs_inlast10_index_bear)*0.5
    if mtvs_inlast15_index_bear < 15
        mtvs_adjusted_bull -= mtvs_best_combo_bull*0.66666*(15-mtvs_inlast15_index_bear)*0.35
    if mtvs_adjusted_bull < 0
        mtvs_adjusted_bull := 0.0
    

    // Large E - bull, removed bear
    large_e_adjusted_bull = large_e_good_weight_bull and (array.get(mtvs_last_index_bull, 1) < 20 or array.get(mtvs_last_index_bull, 2) < 20) ?
     sqrt(large_e_good_weight_bull) + sqrt(max(array.get(mtvs_adjusted_weights_bull, 1), array.get(mtvs_adjusted_weights_bull, 2))) :
     large_e_good_weight_bull*1.3

    
    // Run Up - bull, removed bear
    run_up_index50_bull = index_counter(run_up_bull, 50)
    run_up_weight_bull := run_up_weight_bull < 0.5 ? 1.0 : run_up_weight_bull

    run_up_adjusted_bull = 0.0
    run_up_section_amount_bull = 0
    if run_up_index50_bull >= 5 // decrease: current trend is exhausted
        run_up_adjusted_bull +=  1.35/(sqrt(run_up_weight_bull+0.5)*pow(run_up_index50_bull, 1/5)) 
        run_up_section_amount_bull += 1
    if run_up_last_index_bear >= 100 // decreases: opposite trend IMMENENT
        run_up_adjusted_bull += 1.65/log10(run_up_last_index_bear*run_up_weight_bull) 
        run_up_section_amount_bull += 1
    
    if run_up_index50_bull <= 3 // increase: trend has potential
        run_up_adjusted_bull +=  sqrt(run_up_weight_bull+0.5)
        run_up_section_amount_bull += 1
    if run_up_index50_bear >= 5 // increase: opposite is exhausted
        run_up_adjusted_bull +=  (sqrt(max(run_up_weight_bull, run_up_weight_bear)+0.5)*pow(run_up_index50_bear, 1/5))/1.35
        run_up_section_amount_bull += 1
    if run_up_last_index_bull >= 100 // increase: opposite trend IMMENENT
        run_up_adjusted_bull += log10(run_up_last_index_bull*run_up_weight_bear)/1.65 
        run_up_section_amount_bull += 1
    

    // adjusting weights back - bull, removed bear
    if run_up_section_amount_bull
        run_up_adjusted_bull /= run_up_section_amount_bull
    if run_up_weight_bull == 1.0
        run_up_adjusted_bull := pow(run_up_adjusted_bull, 1/3)
        run_up_weight_bull := 0.0
    run_up_adjusted_bull := not run_up_adjusted_bull ? 1.0 : run_up_adjusted_bull


    // POSITIONS
    // bull, removed bear
    mtvs_pos_bull =
     mtvs_adjusted_bull >= 12 ? 1.0 :
     mtvs_adjusted_bull >= 8  ? map_weight(mtvs_adjusted_bull, 8, 12, 0.3, 1.0) :
     mtvs_adjusted_bull >= 4  ? map_weight(mtvs_adjusted_bull, 4, 8,  0.1, 0.3) :
     0.0

    large_e_pos_bull =
     large_e_adjusted_bull >= 2.0 ? MAX_ENTER :
     large_e_adjusted_bull >= 1.3 ? map_weight(large_e_adjusted_bull, 1.3, 2.0, 0.15, MAX_ENTER) :
     large_e_adjusted_bull >= 1.0 ? map_weight(large_e_adjusted_bull, 1.0, 1.3, 0.10, 0.15) :
     0.0

    mtvd_pos_bull =
     mtvd_adjusted_bull >= 1.5 ? 2.0 :
     mtvd_adjusted_bull >= 1.2 ? map_weight(mtvd_adjusted_bull, 1.2, 1.5, 1.85, 2.0) :
     mtvd_adjusted_bull >= 1.0 ? map_weight(mtvd_adjusted_bull, 1.0, 1.2, 1.65, 1.85) :
     mtvd_adjusted_bull >= 0.6 ? map_weight(mtvd_adjusted_bull, 0.6, 1.0, 1.10, 1.65) :
     mtvd_adjusted_bull >= 0.5 ? map_weight(mtvd_adjusted_bull, 0.5, 0.6, 1.00, 1.10) :
     0.0

    run_up_adj = max(0.5, min(10.0, run_up_adjusted_bull))    
    run_up_pos_bull =
     run_up_adj >= 1.4 ? 1.5 :
     run_up_adj >= 1.0 ? map_weight(run_up_adj, 1.0, 1.4, 1.0, 1.5) :
     run_up_adj >= 0.5 ? map_weight(run_up_adj, 0.5, 1.0, 0.5, 1.0) :
     0.0

    tp_pos_bull =
     tp_aggregated_weight_bull >= 6.2  ? MAX_ENTER :
     tp_aggregated_weight_bull >= 4.0  ? map_weight(tp_aggregated_weight_bull, 4.0, 6.2, 0.33, MAX_ENTER) :
     tp_aggregated_weight_bull >= 0.75 ? map_weight(tp_aggregated_weight_bull, 0.75, 4.0, 0.10, 0.33) :
     0.0

    multiplied_pos_bull = max(mtvs_pos_bull, large_e_pos_bull)*sqrt(mtvd_pos_bull*run_up_pos_bull*good_3x20ema_weight_bull)
    enter_pos_bull =
     multiplied_pos_bull >= 1.5  ? MAX_ENTER :
     multiplied_pos_bull >= 0.85 ? map_weight(multiplied_pos_bull, 0.85, 1.5, 0.25, MAX_ENTER) :
     multiplied_pos_bull >= 0.5  ? map_weight(multiplied_pos_bull, 0.5,  0.85, 0.20, 0.25) :
     multiplied_pos_bull >= 0.2  ? map_weight(multiplied_pos_bull, 0.2,  0.5,  0.10, 0.20) :
     multiplied_pos_bull >= 0.1  ? map_weight(multiplied_pos_bull, 0.1,  0.2,  MIN_ENTER, 0.10) :
     multiplied_pos_bull >= 0.06 ? MIN_ENTER :
     0.0


    [tp_pos_bull, enter_pos_bull]


// Regular Displays
plot(0.87, "1")
plot(0.82, "2", linewidth = 4)
plot(0.72, "3")
// OTHER TF
[tp_pos_15m_bull, enter_pos_15m_bull] = security(syminfo.tickerid, "15", mtv_values(), barmerge.lookahead_on)

pos_tp_trigger = input(false, "----- TPs -----")
enter_trigger = input(false, "----- Enters -----")

minute_15_trigger = input(false, "15 Minute") // removed 5 minutes
// tp
// bull, removed bear
if tp_pos_15m_bull and pos_tp_trigger and minute_15_trigger
    label.new(x=bar_index, y=0.75, yloc=yloc.price, size=size.small,
         text=tostring(decimal_place(tp_pos_15m_bull, 2)),
         textcolor=color.black, color=#42bda8, style=label.style_label_down) 
plot(0.78, "15m", color=not(tp_pos_15m_bull) and barssince(tp_pos_15m_bull) < 15 and minute%15 < 14 and pos_tp_trigger and minute_15_trigger ? #42bda8: na,
 linewidth = 2, style = plot.style_cross)


// enters
// bull, removed bear
enter_text_15m_bull = enter_pos_15m_bull ? tostring(decimal_place(enter_pos_15m_bull, 2)) : ""

if enter_text_15m_bull != "" and enter_trigger and minute_15_trigger
    label.new(x=bar_index, y=0.67, yloc=yloc.price, size=size.small,
         text=enter_text_15m_bull,
         textcolor=color.black, color=color.green, style=label.style_label_down) 
plot(0.7, "15m", color=enter_text_15m_bull == "" and barssince(enter_text_15m_bull != "") < 15 and minute%15 < 14 and enter_trigger and minute_15_trigger ? color.green: na,
 linewidth = 2, style = plot.style_cross)
